### ISSUE TITLE
Can I use this module only using javascript and HTML?

### ISSUE THREAD

**Issue by ghost** [deQuota/chartist-to-image#2]
I'm not using Angular or else, but just javascript and HTML, when I write this 
<script src="./node_modules/chartist-to-image/chartist-to-image.js"></script>
and it makes log that 'require is not defined', but even if I solve this error maybe I could't make any progress.
Can I use this module only using javascript and HTML, or this module is not for me?
I hope small example for line graph.
Thank you for read my bad English.

**Comment by deQuota** [comment]
What is the browser you are using? 
This error happens because 'require' is not there in your browser.
However you can have 'require' working on your browser by doing followings.

1. **npm install -g browserify**

**Comment by deQuota** [comment]
Which browser you are using?

**Comment by ghost** [comment]
I use chrome, and only use javascript and html, but I use node.js express on backend

**Comment by deQuota** [comment]
I have created this module for Angular 2/4/5 and also with React it is working, the problem is there is 'require' function has been called in this module.

However if you need to generate images of Chartist Charts in javascript please use npm module called "Dom-to-image".

It will solve your problem

https://www.npmjs.com/package/dom-to-image

**Comment by ghost** [comment]
OK I will try this. Thank you for make comments on me :)
